Anthony branch post proto
guptat07/Robot-Rumble pull request #10
Opened 2023-07-14 16:11 UTC by aanthonyl

mostly modularized boss, with maya's changes coming it makes more sense to push hers in first she writes beautiful code that organizes everything thank you maya

2023-07-15 00:42 UTC, KayleeConrad requested changes

2023-07-15 00:42 UTC, KayleeConrad commented on robot_rumble/Characters/entities.py
> +        self.character_fadce_direction = constants.RIGHT_FACING
typo added in???

2023-07-15 15:27 UTC, KayleeConrad approved these changes

2023-07-16 08:07 UTC, singh-maya approved these changes

2023-07-16 08:54 UTC, guptat07 approved these changes

2023-07-16 08:54 UTC, merged